spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mysql:8.0.34:///test?TC_INITSCRIPT=file:core/infra/src/testFixtures/resources/init.sql
    username: test
    password: test

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
