spring:
  profiles:
    include: domain, infra, security, testContainers
    active: dev, test
  jpa:
    open-in-view: false # view, Controller 단에서 Lazy를 사용하지 않음
    properties:
      hibernate:
        show_sql: true # sql query console 창에 표시 여부
        format_sql: true # console 창에 보여줄때 format 여부
#  sql:
#    init:
#      mode: always

# default swagger ui url : http://server:port/context-path/swagger-ui.html
springdoc:
  api-docs:
    enabled: true

server:
  port: 8081
  servlet:
    context-path: /v1

logging:
  level:
    org:
      springframework:
        batch: DEBUG
