openapi: 3.0.1
info:
  title: Bag To the Future
  description: API Documentation
  version: 0.1.0
servers:
- url: https://localhost:8080
tags: []
paths:
  /member/register:
    post:
      tags:
      - member
      summary: 회원가입 api
      description: 회원가입 api 입니다.
      operationId: register-member
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/[request] member-register"
            examples:
              register-member:
                value: "{\"password\":\"123456\",\"phoneNumber\":[\"010\",\"1234\"\
                  ,\"5678\"],\"passwordConfirm\":\"123456\",\"name\":\"홍길동\",\"email\"\
                  :\"kildong.hong@naver.com\"}"
      responses:
        "201":
          description: "201"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/[response] member-register"
              examples:
                register-member:
                  value: "{\"code\":201,\"message\":\"정상적으로 생성되었습니다.\",\"data\":{\"\
                    id\":1}}"
components:
  schemas:
    '[request] member-register':
      title: "[request] member-register"
      required:
      - email
      - name
      - password
      - passwordConfirm
      - phoneNumber
      type: object
      properties:
        password:
          type: string
          description: 비밀번호
        phoneNumber:
          type: array
          description: 전화번호
          items:
            oneOf:
            - type: object
            - type: boolean
            - type: string
            - type: number
        passwordConfirm:
          type: string
          description: 비밀번호 확인
        name:
          type: string
          description: 이름
        email:
          type: string
          description: 이메일
    '[response] member-register':
      title: "[response] member-register"
      required:
      - code
      - message
      type: object
      properties:
        code:
          type: number
          description: 응답 코드
        data:
          required:
          - id
          type: object
          properties:
            id:
              type: number
              description: 사용자 ID
        message:
          type: string
          description: 응답 메시지
