openapi: 3.0.1
info:
  title: Bag To the Future
  description: API Documentation
  version: 0.1.0
servers:
- url: http://localhost:8080/v1
tags: []
paths:
  /member/login:
    post:
      tags:
      - member
      summary: 일반 로그인 API
      description: 일반 로그인 API 입니다.
      operationId: login-member
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/[request] member-login"
            examples:
              login-member:
                value: "{\"password\":\"123456\",\"email\":\"kildong.hong@naver.com\"\
                  }"
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/[response] member-login"
              examples:
                login-member:
                  value: "{\"code\":200,\"message\":\"정상 처리되었습니다.\",\"data\":{\"accessToken\"\
                    :\"access token\",\"refreshToken\":\"resfresh token\"}}"
  /member/register:
    post:
      tags:
      - member
      summary: 회원가입 API
      description: 회원가입 API 입니다.
      operationId: register-member
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/[request] member-register"
            examples:
              register-member:
                value: "{\"password\":\"123456\",\"phoneNumber\":[\"010\",\"1234\"\
                  ,\"5678\"],\"passwordConfirm\":\"123456\",\"name\":\"홍길동\",\"email\"\
                  :\"kildong.hong@naver.com\"}"
      responses:
        "201":
          description: "201"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/[response] member-register"
              examples:
                register-member:
                  value: "{\"code\":201,\"message\":\"정상적으로 생성되었습니다.\",\"data\":{\"\
                    id\":1}}"
  /member/business/validate-info:
    post:
      tags:
      - business
      summary: 사업자 정보 유효성 검증
      description: 사업자 정보 유효성 검증 API입니다. (지금은 사용하지 않습니다.)
      operationId: validate-business-info
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/[request] validate-business-info"
            examples:
              validate-business-info:
                value: "{\"businessNumber\":\"0000000000\",\"startDate\":\"20000101\"\
                  ,\"name\":\"홍길동\",\"name2\":\"홍길순\",\"businessName\":\"(주)테스트\"\
                  ,\"corporationNumber\":\"0000000000000\",\"businessSector\":\"\"\
                  ,\"businessType\":\"\",\"businessAddress\":\"\"}"
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/[response] validate-business-info"
              examples:
                validate-business-info:
                  value: "{\"code\":200,\"message\":\"정상 처리되었습니다.\",\"data\":{\"isValid\"\
                    :true}}"
  /member/business/validate-status:
    post:
      tags:
      - business
      summary: 사업자 번호 상태 검증
      description: 사업자 번호 상태 검증 API입니다.
      operationId: business-number-status
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/[request] business-number-status"
            examples:
              business-number-status:
                value: "{\"businessNumber\":\"0000000000\"}"
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/[response] business-number-status"
              examples:
                business-number-status:
                  value: "{\"code\":200,\"message\":\"정상 처리되었습니다.\",\"data\":{\"isValid\"\
                    :true}}"
  /member/login/oauth:
    post:
      tags:
      - member
      summary: 소셜 로그인 API
      description: 소셜 로그인 API 입니다.
      operationId: oauth-login
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OAuthLoginDto'
            examples:
              oauth-login:
                value: "{\"authorizationCode\":\"authorizationCode\",\"providerType\"\
                  :\"KAKAO\",\"rolesType\":\"ROLE_USER\",\"state\":\"state\",\"token\"\
                  :\"accessToken\"}"
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginTokenDto'
              examples:
                oauth-login:
                  value: "{\"code\":200,\"message\":\"정상 처리되었습니다.\",\"data\":{\"accessToken\"\
                    :\"accessToken\",\"refreshToken\":\"resfreshToken\"}}"
components:
  schemas:
    '[response] validate-business-info':
      title: "[response] validate-business-info"
      required:
      - code
      - message
      type: object
      properties:
        code:
          type: number
          description: 응답 코드
        data:
          required:
          - isValid
          type: object
          properties:
            isValid:
              type: boolean
              description: 유효성 검사 결과
        message:
          type: string
          description: 응답 메시지
    '[request] business-number-status':
      title: "[request] business-number-status"
      required:
      - businessNumber
      type: object
      properties:
        businessNumber:
          type: string
          description: 사업자번호
    '[response] business-number-status':
      title: "[response] business-number-status"
      required:
      - code
      - message
      type: object
      properties:
        code:
          type: number
          description: 응답 코드
        data:
          required:
          - isValid
          type: object
          properties:
            isValid:
              type: boolean
              description: 상태 검증 결과
        message:
          type: string
          description: 응답 메시지
    '[request] member-register':
      title: "[request] member-register"
      required:
      - email
      - name
      - password
      - passwordConfirm
      - phoneNumber
      type: object
      properties:
        password:
          type: string
          description: 비밀번호
        phoneNumber:
          type: array
          description: 전화번호
          items:
            oneOf:
            - type: object
            - type: boolean
            - type: string
            - type: number
        passwordConfirm:
          type: string
          description: 비밀번호 확인
        name:
          type: string
          description: 이름
        email:
          type: string
          description: 이메일
    OAuthLoginDto:
      title: OAuthLoginDto
      required:
      - authorizationCode
      - providerType
      - rolesType
      type: object
      properties:
        rolesType:
          type: string
          description: "유저의 자격 값입니다. ( 관리자 : ROLE_ADMIN, 일반 회원 : ROLE_USER, 가게 회원\
            \ : ROLE_STORE_OWNER )"
        authorizationCode:
          type: string
          description: Authorization Server에서 받은 인증 코드입니다.
        state:
          type: string
          description: 네이버 소셜 로그인 시 필요한 state 값입니다. 'state' string 주면 됩니다. ( KAKAO
            로그인 시 null )
          nullable: true
        providerType:
          type: string
          description: "어떤 소셜 로그인인지 입력 값입니다. ( 카카오 로그인 : KAKAO, 네이버 로그인 : NAVER )"
        token:
          type: string
          description: 소셜 인증 서버에서 발급받은 접근 토큰 값입니다.
          nullable: true
    '[request] member-login':
      title: "[request] member-login"
      required:
      - email
      - password
      type: object
      properties:
        password:
          type: string
          description: 비밀번호
        email:
          type: string
          description: 이메일
    '[response] member-login':
      title: "[response] member-login"
      required:
      - code
      - message
      type: object
      properties:
        code:
          type: number
          description: 응답 코드
        data:
          required:
          - accessToken
          - refreshToken
          type: object
          properties:
            accessToken:
              type: string
              description: Access Token
            refreshToken:
              type: string
              description: Refresh Token
        message:
          type: string
          description: 응답 메시지
    LoginTokenDto:
      title: LoginTokenDto
      required:
      - code
      - message
      type: object
      properties:
        code:
          type: number
          description: 응답 코드
        data:
          required:
          - accessToken
          - refreshToken
          type: object
          properties:
            accessToken:
              type: string
              description: Access Token
            refreshToken:
              type: string
              description: Refresh Token
        message:
          type: string
          description: 응답 메시지
    '[response] member-register':
      title: "[response] member-register"
      required:
      - code
      - message
      type: object
      properties:
        code:
          type: number
          description: 응답 코드
        data:
          required:
          - id
          type: object
          properties:
            id:
              type: number
              description: 사용자 ID
        message:
          type: string
          description: 응답 메시지
    '[request] validate-business-info':
      title: "[request] validate-business-info"
      required:
      - businessAddress
      - businessName
      - businessNumber
      - businessSector
      - businessType
      - name
      - startDate
      type: object
      properties:
        businessSector:
          type: string
          description: 주업태명
        corporationNumber:
          type: string
          description: 법인등록번호
          nullable: true
        businessName:
          type: string
          description: 상호
        name:
          type: string
          description: 대표자 성명
        businessNumber:
          type: string
          description: 사업자번호
        businessAddress:
          type: string
          description: 사업장주소
        businessType:
          type: string
          description: 주종목명
        name2:
          type: string
          description: 대표자 성명2
          nullable: true
        startDate:
          type: string
          description: 개업일자
